apiVersion: v1
kind: Secret
metadata:
  name: nkvm-remote-kubeconfig
  namespace: nerdy-k8s-volume-manager
  labels:
    app.kubernetes.io/name: nerdy-k8s-volume-manager
type: Opaque
stringData:
  # Mounts to /etc/nkvm/remote/config in the app pod.
  config: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: remote-cluster
        cluster:
          server: https://remote-api.example.com:6443
          certificate-authority-data: REPLACE_WITH_BASE64_CA_BUNDLE
    contexts:
      - name: remote-cluster
        context:
          cluster: remote-cluster
          user: remote-user
    current-context: remote-cluster
    users:
      - name: remote-user
        user:
          token: REPLACE_WITH_TOKEN
