apiVersion: v1
kind: Service
metadata:
  name: nerdy-k8s-volume-manager
  namespace: nerdy-k8s-volume-manager
  labels:
    app.kubernetes.io/name: nerdy-k8s-volume-manager
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nerdy-k8s-volume-manager
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: 80
      targetPort: http
      appProtocol: http
      protocol: TCP
